---
include:
  - project: nofusscomputing/projects/gitlab-ci
    ref: development
    file:
      - .gitlab-ci_common.yaml
      - template/automagic.gitlab-ci.yaml

variables:
  MY_PROJECT_ID: "51640029"
  GIT_SYNC_URL: "https://$GITHUB_USERNAME_ROBOT:$GITHUB_TOKEN_ROBOT@github.com/NoFussComputing/ansible_role_nfc_kubernetes.git"
  PAGES_ENVIRONMENT_PATH: projects/ansible/roles/kubernetes/


Ansible-roles.Submodule.Deploy:
  extends: .submodule_update_trigger
  variables:
    SUBMODULE_UPDATE_TRIGGER_PROJECT: nofusscomputing/projects/ansible/ansible-roles
    GIT_COMMIT_TYPE: feat
    GIT_COMMIT_TYPE_CATEGORY: $CI_PROJECT_NAME
    GIT_CONFIG_SUBMODULE_NAME: nfc_kubernetes
