INHERIT: website-template/mkdocs.yml

docs_dir: 'docs'

repo_name: Git Configuration
repo_url: https://gitlab.com/nofusscomputing/projects/ansible/git_configuration
edit_uri: '/-/ide/project/nofusscomputing/projects/ansible/git_configuration/edit/development/-/docs/'

nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - Ansible:

    - Roles:

      - Kubernetes:

        - projects/ansible/roles/kubernetes/index.md

        - projects/ansible/roles/kubernetes/firewall.md


- Operations: 

  - operations/index.md

- Contact Us: contact.md

