INHERIT: website-template/mkdocs.yml

docs_dir: 'docs'

repo_name: Kubernetes Ansible Role
repo_url: https://gitlab.com/nofusscomputing/projects/ansible/kubernetes
edit_uri: '/-/ide/project/nofusscomputing/projects/ansible/kubernetes/edit/development/-/docs/'

nav:
- Home: index.md

- Articles: 

  - articles/index.md

- Projects: 

  - projects/index.md

  - Ansible:

    - projects/ansible/index.md

    - Execution Environment:

      - projects/ansible/execution_environment/index.md

    - Playbooks:

      - projects/ansible/playbooks/index.md

    - Roles:

      - projects/ansible/roles/index.md

      - Kubernetes:

        - projects/ansible/roles/kubernetes/index.md

        - projects/ansible/roles/kubernetes/ansible.md

        - projects/ansible/roles/kubernetes/firewall.md

        - projects/ansible/roles/kubernetes/rbac.md


- Operations: 

  - operations/index.md

- Contact Us: contact.md

