---
# kubernetes_installed

- name: K3s Install
  ansible.builtin.include_tasks:
    file: k3s/install.yaml
    apply:
      tags:
        - always
  when: >
    install_kubernetes | default(true) | bool
      and
    not kubernetes_installed | default(false) | bool
  tags:
    - never
    - install
    - operator_calico
    - operator_migrate_calico


- name: K3s Configure
  ansible.builtin.include_tasks:
    file: k3s/configure.yaml
    apply:
      tags:
        - always
  when: >
    install_kubernetes | default(true) | bool
      and
    kubernetes_installed | default(false) | bool
  tags:
    - never
    - install
    - operator_migrate_calico
