---
# kubernetes_installed

- name: K3s Install
  ansible.builtin.include_tasks:
    file: k3s/install.yaml
  when: >
    install_kubernetes | default(true) | bool
      and
    not kubernetes_installed | default(false) | bool


- name: K3s Configure
  ansible.builtin.include_tasks:
    file: k3s/configure.yaml
  when: >
    install_kubernetes | default(true) | bool
      and
    not kubernetes_installed | default(false) | bool
