---
# - name: configure non-prime nodes - check node health
#   shell: "curl http://localhost:10248/healthz || true"
#   register: health
#   changed_when: true == false

# - set_fact:
#     kube_joined: "{{ health.stdout == 'ok' }}"
#   changed_when: true == false
#   # when: 
#   #     - not Kubernetes_Prime

- name: configure non-prime nodes - create remote workdir
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  changed_when: true == false
  with_items:
    - /tmp/ansible/


- ansible.builtin.shell: " wget http://localhost:10248/healthz -q -O - || true"
  register: health
  changed_when: true == false


- set_fact:
    kube_joined: "{{ health.stdout == 'ok' }}"
  changed_when: true == false


- name: get join command from ansible controller
  copy:
    src: /tmp/ansible/join_kubernetes.sh
    dest: /tmp/ansible/join_kubernetes.sh
    mode: 0700
  changed_when: true == false
  when: 
    - not kube_joined


- name: configure non-prime nodes - join node to kubernetes cluster
  command: sh /tmp/ansible/join_kubernetes.sh
  when: 
    - not kube_joined
